# Configuration du Backend
backend:
  replicas: 1
  image: docker.io/boritos/backend
  tag: "app-3tiers-pipeline-362o1o"
  db:
    url: "jdbc:mariadb://mariadb-local:3306/ma_base"
    user: "admin"
    password: "admin"

# Configuration du Frontend
frontend:
  replicas: 1
  image: docker.io/boritos/frontend
  tag: "app-3tiers-pipeline-362o1o"
