apiVersion: v1
kind: Service
metadata:
  name: mariadb-local
  namespace: demo-188
spec:
  ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    deployment: mariadb-local
